GET http://localhost:4000/register

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "Username" : "vicky",
    "Email" : "vicky@gmail.com",
    "Password": "password"
}

###

POST http://localhost:3000/post/login
Content-Type: application/json

{
 "user" : "vicky",
 "password": "password"
}